apiVersion: v1
kind: Pod
metadata:
  name: active-mq-pod
  labels:
    app: active-mq-pod
spec:
  containers:
    - name: active-mq-pod
      image: richardchesterwood/k8s-fleetman-queue:release1
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
