apiVersion: v1
kind: Pod
metadata:
  name: webapp
  labels:
    label-app: webapp
    label-release: "0"
spec:
  containers:
    - name: webapp
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0
      imagePullPolicy: IfNotPresent
  restartPolicy: Always

---

apiVersion: v1
kind: Pod
metadata:
  name: webapp-release0-5
  labels:
    label-app: webapp
    label-release: "0-5"
spec:
  containers:
    - name: webapp
      image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
      imagePullPolicy: IfNotPresent
  restartPolicy: Always
