apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  selector:
    matchLabels:
      app: api-gateway
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway
          resources:
            requests:
              cpu: 50m
              memory: 200Mi
          image: richardchesterwood/k8s-fleetman-api-gateway:performance
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: production-microservice



