apiVersion: apps/v1
kind: ReplicaSet
metadata:
  # Unique key of the ReplicaSet instance
  name: udemy-k8s-aws-replicaset-webapp
spec:
  # 3 Pods should exist at all times.
  replicas: 3
  selector:
    matchLabels:
      label-app: rs-pod-webapp
      label-release: 0-5
  # label-release: 0-5
  template:
    metadata:
      labels:
        label-app: rs-pod-webapp
        label-release: 0-5
    spec:
      containers:
      - name: rs-pod-webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
